[project]
name = "market-data-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.4",
    "uvicorn>=0.38.0",
    "yfinance>=0.2.66",
]
